# Create a geo-coordinates file by postal code for Toronto
* Import the necessary python libraries
* Read the data into a dataframe and check out the format

In [1]:
import pandas as pd
import numpy  as np
df_geo = pd.read_csv('http://cocl.us/Geospatial_data')
df_geo.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

#### Import the Toronto postal codes data from the previous exercise
* read the csv file into a dataframe 
* remove the unwanted addtional index column
* check the output using the head method

In [2]:
df_pcd = pd.read_csv('toronto_postal_codes.csv')
df_pcd.drop(columns='Unnamed: 0',inplace=True)
df_pcd.head()

  PostalCode      Borough        Neighbourhood
0        M1G  Scarborough               Woburn
1        M1H  Scarborough            Cedarbrae
2        M1J  Scarborough  Scarborough Village
3        M1S  Scarborough            Agincourt
4        M1X  Scarborough          Upper Rouge

#### Merge the two dataframes into one
* Join the two dataframes based on the PostalCode column (df_pcd.PostalCode) (left hand side_
* Join the 'right' dataframe df_geo containing the geo-coordinates by postal code using the 'Postal Code' column
* how = 'left' = based the join on the df_pcd column

In [3]:
# merge the two dataframes
df_pcd = df_pcd.merge(df_geo,left_on='PostalCode',right_on='Postal Code',how='left')
df_pcd.head()

,PostalCode,Borough,Neighbourhood,Postal Code,Latitude,Longitude
0,M1G,Scarborough,Woburn,M1G,43.770992,-79.216917
1,M1H,Scarborough,Cedarbrae,M1H,43.773136,-79.239476
2,M1J,Scarborough,Scarborough Village,M1J,43.744734,-79.239476
3,M1S,Scarborough,Agincourt,M1S,43.794200,-79.262029
4,M1X,Scarborough,Upper Rouge,M1X,43.836125,-79.205636

#### Drop the second postal code column after validating

In [4]:
# drop the second postal code column after verifying
df_pcd.drop(columns='Postal Code',inplace=True)
#df_pcd.columns
df_pcd.head(11)

   PostalCode      Borough        Neighbourhood   Latitude  Longitude
0         M1G  Scarborough               Woburn  43.770992 -79.216917
1         M1H  Scarborough            Cedarbrae  43.773136 -79.239476
2         M1J  Scarborough  Scarborough Village  43.744734 -79.239476
3         M1S  Scarborough            Agincourt  43.794200 -79.262029
4         M1X  Scarborough          Upper Rouge  43.836125 -79.205636
5         M2H   North York    Hillcrest Village  43.803762 -79.363452
6         M2K   North York      Bayview Village  43.786947 -79.385975
7         M2N   North York     Willowdale South  43.770120 -79.408493
8         M2P   North York      York Mills West  43.752758 -79.400049
9         M2R   North York      Willowdale West  43.782736 -79.442259
10        M3A   North York            Parkwoods  43.753259 -79.329656

#### The number of rows should be the same as the original

In [5]:
df_pcd.shape

(103, 5)